<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNjdBZMR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNjdBZMR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNjdBZMR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNjdBZMR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNjdBZMR\App_KernelDevDebugContainer([
    'container.build_hash' => 'NjdBZMR',
    'container.build_id' => '4730e883',
    'container.build_time' => 1649167027,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNjdBZMR');
